### ISSUE TITLE
Make user table

### ISSUE THREAD

**Issue by zmays** [okcoders/study#2]
table should have following columns:

- name: populated with name or username
- latest commit date
- number of commits

Table should by default be sorted by latest commit date desc

**Comment by julesep3** [comment]
I got a  basic table set up with 3 columns: name, number of commits, and latest commit date. 

Started by looking up tables in Material-UI, copied the relevant code to the project, and then fiddled with getting the right information in the right spots. I am still needing to figure the sorting out.

**Comment by julesep3** [comment]
`app.get("/api/github-profiles", async (req, res) => {
  const usernames = [
    "zmays",
    "almills1972",
    "hamza-zoumhani",
    "johnmwaura08",
    "julesep3",
    "rbaptiste23",
    "robdacoda"
  ];
  const usernamePromises = usernames.map(getProfileAndEvents);
  var preSortedData = await Promise.all(usernamePromises);
  const data = preSortedData.commit.sort(function(a, b) {
    return b - a;
  });
  res.json(data);
});`

**Comment by julesep3** [comment]
I tried sorting the 'data' inside the app.get function for app.js in the server by sorting the array of fulfilled promises before the data gets sent to App.js. I assumed that since it returns an array of objects, I should be able to sort the array based on the 'latestCommitDate' key. No luck.

**Comment by zmays** [comment]
sorry just saw this.

**Comment by zmays** [comment]
I just pushed code that has the table stuff, I did it all on the front end, check it out
